server:
  port: 8080
#  servlet:
#    context-path: /crm

spring:
  application:
    name: TESTspringboot
#  resources:
#    static-locations: classpath:/
#  freemarker:
#    template-loader-path: classpath:/templates/
#    suffix: .html
#    content-type: text/html
#    charset: UTF-8
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/java0608?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
#  mvc:
#    static-path-pattern: /static/**

mybatis:
  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.hjf.entity
  config-location: classpath:mybatis-config.xml

logging:
  level:
    com.hjf.mapper: debug

pagehelper:
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  helper-dialect: mysql

datapro:
  num: 1
  flag: false
  str: 张三
  list:
    - 1
    - 2
    - 3
  map: {"name":张三,"age":22}
  role:
    roleid: 1
    rolename: 张三
    roleinfo: admin






